import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import search from "../assets/searchicon.png";
import bell from "../assets/notification.png";
import background from "../assets/background.png";
import avatar from "../assets/avatar.png";
import verified from "../assets/verifiedicon.png";
import ProfileDetails from "../Components/ProfileDetails";
import ProfileSubDetails from "../Components/ProfileSubDetails";
import location from "../assets/mark.png";
import bag from "../assets/case.png";
import fire from "../assets/fire.png";
const Home: NextPage = () => {
  return (
    <div className={styles.maincontainer}>
      <Head>
        <title>profilewidget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <div className={styles.subcontainer}>
        <div className={styles.innercontainer}>
          <header className={styles.headercontainer}>
            <Image src={search} width={24} height={26}></Image>
            <Image
              src={bell}
              width={24}
              height={24}
              objectFit="contain"
            ></Image>
          </header>
          <div className={styles.mainimagecontainer}>
            <div className={styles.imagecontainer}>
              <Image
                className={styles.img}
                src={background}
                objectFit="cover"
              ></Image>
            </div>
            <div className={styles.avatarcontainer}>
              <Image src={avatar} width={110} height={110}></Image>
            </div>
          </div>
          <div className={styles.profilenamecontainer}>
            <h1 className={styles.profilename}>John Westfield</h1>
            {/* <div className={styles.verifiedcontainer}> */}
            <Image
              src={verified}
              width={20}
              height={20}
              objectFit="contain"
              // layout="responsive"
            ></Image>
            {/* </div> */}
          </div>
          <div className={styles.descriptioncontainer}>
            <p className={styles.description}>
              I am interested in building projects,travelling and biking.
            </p>
          </div>
          <div className={styles.profilecontainer}>
            <ProfileDetails
              count={150}
              text="Following"
              className="followingcount"
              classname="followingtext"
            />
            <ProfileDetails
              count={43.15}
              text="Followers"
              className="followerscount"
              classname="followingtext"
            />
            <ProfileDetails
              count={163}
              text="Posts"
              className="followingcount"
              classname="followingtext"
            />
          </div>
          <div className={styles.buttoncontainer}>
            <button className={styles.btn}>Follow Me</button>
          </div>
          <div className={styles.subdetailscontainer}>
            <ProfileSubDetails
              image={location}
              details="Lives in Budapest"
              classname="placetext"
            />
            <ProfileSubDetails
              image={bag}
              details="Works as Full Stack Developer at Google."
              classname="placetext"
            />
            <ProfileSubDetails
              image={fire}
              details="ReactJs,NodeJs,MongoDB and Devops"
              classname="placetext"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
